name: Проверка проекта

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Получение исходного кода
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Установка Poetry
        run: pip install poetry==2.4.1

      - name: Установка зависимостей
        run: poetry install --no-interaction --no-ansi

      - name: Проверка Black
        run: poetry run black --check src tests

      - name: Проверка isort
        run: poetry run isort --check-only src tests

      - name: Проверка Flake8
        run: poetry run flake8 src tests

      - name: Проверка mypy
        run: poetry run mypy src tests

      - name: Запуск тестов
        run: poetry run pytest --cov=src/protogen_delta --cov-report=term-missing